version: '2'

services:
  vue-dev:
    container_name: vue-dev-env
    image: vue-dev-env
    volumes:
    - $PWD:/usr/src/app
    - /usr/src/app/node_modules
    #network_mode:  "host"
    command: npm run serve   
    ports: 
    - "8080:8080"